spring:
  profiles:
    active: dev
  application:
    name: dy_xhs_monitor
  datasource:
    url: jdbc:sqlite:C:/Users/wuyua/Downloads/dy_xhs_monitor/ds.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
api:
  parse-main-api: https://api.cenguigui.cn/api/douyin/userinfo.php?url=
  zp-url: https://www.douyin.com/user/
  proxy-url: http://abc.com #换成自己获取代理ip 的地址
  zp-count-url: https://api.douyin.wtf/api/douyin/web/handler_user_profile?sec_user_id=
  xhs-url: https://www.xiaohongshu.com/user/profile/
  app-token: ATABCCCCCCC # #换成自己获取 app token
  send-message-url: https://wxpusher.zjiecode.com/api/send/message
  bibi-url: https://api.douyin.wtf/api/bilibili/web/fetch_user_post_videos?pn=1&uid=
  qsy-url: https://api.emoboy.vip/api/shuiyin/delWatermark?key=ba2eca35-4d96-9cb8-c217f2bc&url=
# http://api.mmp.cc/api/dyhome?url=
# https://api.aa1.cn/doc/douyinauthor.html
# https://api.makuo.cc/
# https://api.mir6.com/api/bzjiexi?url=https://www.bilibili.com/video/BV1umNXzfE3K/
server:
  port: 8888