spring:
  application:
    name: dy_xhs_monitor
  datasource:
    url: jdbc:sqlite:C:/httprunner/demo/pf4j/dy_xhs_monitor/ds.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
api:
  parse-main-api: https://api.cenguigui.cn/api/douyin/userinfo.php?url=
  zp-url: https://www.douyin.com/user/
  proxy-url: http://abc.com #换成自己获取代理ip 的地址
  zp-count-url: https://api.douyin.wtf/api/douyin/web/handler_user_profile?sec_user_id=
  xhs-url: https://www.xiaohongshu.com/user/profile/
  app-token: ATABCCCCCCC # #换成自己获取 app token
  send-message-url: https://wxpusher.zjiecode.com/api/send/message
  bibi-url: https://api.douyin.wtf/api/bilibili/web/fetch_user_post_videos?pn=1&uid=
# http://api.mmp.cc/api/dyhome?url=
# https://api.aa1.cn/doc/douyinauthor.html
# https://api.makuo.cc/
server:
  port: 8888